
server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
