
server:
  port: 9024
spring:
  application:
    name: caller_details
#  data:
#    solr:
#      host: http://localhost:9010/solr/collection1
  redis:
      database: 2
      host: 127.0.0.1
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true