
server:
  port: 9020
spring:
  application:
    name: caller
  data:
    solr:
      host: http://localhost:9010/solr/collection1
  redis:
      database: 0
      host: 127.0.0.1
      port: 6379
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka


#两个微服务之间调用feign
#超时的解决
#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000

#  hystrix:
#feign:
#  httpclient:
#    connection-timeout: 10000

#    enabled: true